app = "audiobook-maker-api"
primary_region = "iad"

[build]

[env]
  ALLOWED_ORIGINS = "https://audiobook-maker.shaneweickum.com"

[[mounts]]
  source = "audiobook_data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
